// Generated by CoffeeScript 1.3.3
(function() {

  (function(Karmr) {
    Karmr = Karmr || {};
    Karmr.websocket = Karmr.websocket || {};
    Karmr.protocol = window.location.protocol;
    Karmr.domain = window.location.host;
    Karmr.socket = io.connect(Karmr.protocol + "//" + Karmr.domain);
    Karmr.socket.on("api", function(data) {
      return console.log("api", JSON.stringify(data));
    });
    Karmr.socket.on("connect", function(data) {
      console.log("CONNECTED", data);
      Karmr.accounts = new Accounts(Karmr.socket);
      Karmr.accounts.subscribe("sessioning", function(data) {
        return console.log("SESSIONING", data);
      });
      Karmr.accounts.subscribe("sessioned", function(data) {
        return console.log("SESSIONED", data);
      });
      Karmr.accounts.subscribe("unsessioned", function(data) {
        return console.log("UNSESSIONED", data);
      });
      return Karmr.accounts.subscribe("profile", function(data) {
        return console.log("PROFILE", data);
      });
    });
    return Karmr.socket.on("disconnect", function() {
      return console.log("DISCONNECTED");
    });
  })(Karmr || {});

}).call(this);
