// Generated by CoffeeScript 1.3.3
(function() {
  var Karmr;

  Karmr = function(_namespace, callback) {
    _namespace = _namespace || {};
    _namespace.websocket = _namespace.websocket || {};
    _namespace.protocol = window.location.protocol;
    _namespace.domain = window.location.host;
    _namespace.socket = io.connect(_namespace.protocol + "//" + _namespace.domain);
    _namespace.socket.on("api", function(data) {
      return console.log("api", JSON.stringify(data));
    });
    _namespace.socket.on("connect", function(data) {
      console.log("CONNECTED", data);
      _namespace.accounts = new Accounts(_namespace.socket);
      callback.apply(this, _namespace.accounts);
      _namespace.accounts.subscribe("sessioning", function(data) {
        return console.log("SESSIONING", data);
      });
      _namespace.accounts.subscribe("sessioned", function(data) {
        return console.log("SESSIONED", data);
      });
      _namespace.accounts.subscribe("unsessioned", function(data) {
        return console.log("UNSESSIONED", data);
      });
      return _namespace.accounts.subscribe("profile", function(data) {
        return console.log("PROFILE", data);
      });
    });
    _namespace.socket.on("disconnect", function() {
      return console.log("DISCONNECTED");
    });
    return window.Karmr = _namespace;
  };

  Karmr({}, function(accounts) {
    /*
      Run
    */

    var header_view, main_view;
    header_view = new HeaderView(accounts);
    return main_view = new MainView;
  });

}).call(this);
